#配置数据源
spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/demo_03
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
#配置jpa  
jpa: 
  database: MySQL
  show-sql: true
  hibernate: 
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  